---
# tasks file for common

- name: Check to see if curl is already installed
  command: "curl --version"
  ignore_errors: true
  changed_when: false
  check_mode: no
  register: curl_installed

- name: install python pip
  become: yes
  action: >
    {{ ansible_pkg_mgr }} name=curl state=present
  when: curl_installed.rc != 0

- name: Check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  changed_when: false
  check_mode: no
  register: pip_installed

- name: install python pip
  become: yes
#   action: >
#     {{ ansible_pkg_mgr }} name={{ item }} state=present
#   with_items:
#     - "{{ pkgs[ansible_os_family | lower] }}"
#   when: ansible_os_family != 'Darwin'
  shell: curl https://bootstrap.pypa.io/get-pip.py | python
  when: pip_installed.rc != 0
