---
# tasks file for roles/sdkman

- name: check sdkman installation
  stat: path="{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman

- name: install sdkman
  # shell: curl -s "https://get.sdkman.io" | bash
  # when: not sdkman.stat.exists
  script: get-sdkman.sh
  register: iresult

- name: check installation status
  fail: msg="failed to install sdkman!"
  when: "'Enjoy!' not in iresult.stdout"
