---
# tasks file for roles/javascript

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  args:
    creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'

- name: install node
  shell: 'source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}'
  with_items: [ '{{ node_install_list }}' ]

# TODO: set default

- name: get the path of default node
  shell: 'source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use --lts && which node'
  # with_items: [ '{{ node_install_list }}' ]
  # notify: show node info
  register: nodes_info

# - set_fact:
#   vars:
#     exec_list:
#   args:
#     exec_list: '{{ exec_list }} [bb]'
#   with_items: [ '{{ nodes_info.results }}' ]
#
# - debug:
#     msg: '{{ exec_list }}'

- name: install JavaScript utilities
  vars:
    bin_dir: '{{ nodes_info.stdout_lines[1] | dirname }}'
  npm:
    name: '{{ item }}'
    global: yes
    state: present
    # registry: https://registry.npm.taobao.org
    executable: '{{ bin_dir }}/npm'
  environment:
    NVM_DIR: '{{ ansible_env.HOME }}/.nvm'
    PATH: '{{ bin_dir }}:{{ ansible_env.PATH }}'
  with_items: ['{{ util_install_list }}']
