---
# tasks file for roles/javascript

- name: check nvm installation
  stat: path="{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_sh

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  when: not nvm_sh.stat.exists

- name: check nvm installation
  stat: path="{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_sh

- name: check installation status
  fail: msg="failed to install nvm!"
  when: not nvm_sh.stat.exists

- name: install node latest
  shell: nvm install node

- name: install node lts
  shell: nvm install --lts

- name: install cnpm/yarn/typescript
  npm:
    name: {{ item }}
    registry: https://registry.npm.taobao.org
    global: yes
    state: absent
  with_items:
    - cnpm
    - yarn
    - typescript
