---
# tasks file for roles/javascript

- name: check nvm installation
  stat: path="{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_sh

- name: install nvm
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  when: not nvm_sh.stat.exists

- name: check nvm installation
  stat: path="{{ ansible_env.HOME }}/.nvm/nvm.sh"
  register: nvm_sh

- name: check installation status
  fail: msg="failed to install nvm!"
  when: not nvm_sh.stat.exists

- name: install node (latest and lts)
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}"
  with_items:
    - node
    - --lts

# TODO: install for each node
- name: change default node to lts (FIXME)
  shell: 'source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use --lts'

- name: get the path of default node
  shell: 'source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm which node'
  register: node

- set_fact:
    node_bin: '{{ node.stdout | dirname }}'

- debug:
    msg: '{{ node_bin }}'

- name: install JavaScript utilities
  npm:
    name: '{{ item }}'
    global: yes
    state: present
    # registry: https://registry.npm.taobao.org
    executable: '{{ node_bin }}/npm'
  environment:
    NVM_DIR: '{{ ansible_env.HOME }}/.nvm'
    PATH: '{{ node_bin }}:{{ ansible_env.PATH }}'
  with_items:
    - yarn
    - cnpm
    - typescript
    - bower
    - grunt
    - gulp
