---
- hosts: all

  # vars:
  #   proxy_env:
  #     http_proxy:  127.0.0.1:52016
  #     https_proxy: 127.0.0.1:52016
  #     socks_proxy: 127.0.0.1:52017

  # vars_files:
  #   - "vars/{{ ansible_os_family | lower }}.yml"

  roles:
    - common
    - python
    - java
    - javascript

  environment:
    http_proxy:  '{{http_proxy | default ("") }}'
    https_proxy: '{{https_proxy | default ("") }}'
    socks_proxy: '{{socks_proxy | default ("") }}'
    no_proxy:    '{{no_proxy | default ("") }}'
